Repository bitcoin-core/secp256k1, pull requests merged in 2023-11, with the labels that each got.

#1184 Signed-digit based ecmult_const algorithm
  CHANGELOG.md
  src/bench_internal.c
  src/ecmult_const_impl.h
  src/scalar.h
  src/scalar_4x64_impl.h
  src/scalar_8x32_impl.h
  src/scalar_low.h
  src/scalar_low_impl.h
  src/tests.c
Labels: performance, refactor/smell

#1442 Return temporaries to being unsigned in secp256k1_fe_sqr_inner
  src/field_5x52_int128_impl.h
Labels: assurance, refactor/smell

#1441 asm: add .note.GNU-stack section for non-exec stack
  src/asm/field_10x26_arm.s
Labels: build, refactor/smell

#1445 bench: add --help option to bench_internal
  src/bench_internal.c
Labels: refactor/smell

#1438 correct assertion for secp256k1_fe_mul_inner
  src/field_5x52_int128_impl.h
Labels: assurance, refactor/smell
