Repository bitcoin-core/secp256k1, pull requests merged in 2023-05, with the labels that each got.

#1303 ct: Use more volatile
  src/ecmult_const_impl.h
  src/modinv32_impl.h
  src/modinv64_impl.h
  src/scalar_4x64_impl.h
  src/scalar_8x32_impl.h
Labels: bug, assurance, side-channel

#1306 build: Make tests work with external default callbacks
  src/tests.c
  src/tests_exhaustive.c
Labels: build

#1304 build: Rename arm to arm32 and check if it's really supported
  .cirrus.yml
  CMakeLists.txt
  build-aux/m4/bitcoin_secp.m4
  cmake/CheckArm32Assembly.cmake
  cmake/CheckX86_64Assembly.cmake
  cmake/source_arm32.s
  configure.ac
  src/CMakeLists.txt
Labels: build, needs-changelog

#1307 Mark more assembly outputs as early clobber
  CHANGELOG.md
  src/field_5x52_asm_impl.h
  src/scalar_4x64_impl.h
Labels: bug, needs-changelog

#1318 build: Enable -DVERIFY for precomputation binaries
  Makefile.am
Labels: assurance, build

#1333 test: Warn if both `VERIFY` and `COVERAGE` are defined
  src/tests.c
Labels: assurance, build
