Repository bitcoin-core/secp256k1, pull requests merged in 2023-08, with the labels that each got.

#1389 ci: Run "Windows (VS 2022)" job on GitHub Actions
  .github/workflows/ci.yml
Labels: ci

#1400 ctimetests: Use new SECP256K1_CHECKMEM macros also for ellswift
  .cirrus.yml
  src/ctime_tests.c
Labels: ci, side-channel, refactor/smell

#1348 tighten group magnitude limits, save normalize_weak calls in group add methods (revival of #1032)
  src/field.h
  src/field_impl.h
  src/group.h
  src/group_impl.h
  src/tests.c
Labels: assurance, performance

#1402 ci: Use Homebrew's gcc in native macOS task
  .cirrus.yml
  ci/cirrus.sh
Labels: ci

#1274 test: Silent noisy clang warnings about Valgrind code on macOS x86_64
  src/checkmem.h
Labels: build

#1394 ci, gha: Run "x86_64: macOS Ventura" job on GitHub Actions
  .github/workflows/ci.yml
Labels: ci

#1404 ci: Remove "arm64: macOS Ventura" task from Cirrus CI
  .cirrus.yml
  .github/workflows/ci.yml
Labels: ci

#1062 Removes `_fe_equal_var`, and unwanted `_fe_normalize_weak` calls (in tests)
  src/field.h
  src/field_impl.h
  src/group_impl.h
  src/modules/extrakeys/tests_exhaustive_impl.h
  src/modules/schnorrsig/main_impl.h
  src/tests.c
  src/tests_exhaustive.c
Labels: refactor/smell

#1401 ci, gha: Run all MSVC tests on Windows natively
  .cirrus.yml
  .github/workflows/ci.yml
  ci/cirrus.sh
  ci/linux-debian.Dockerfile
Labels: ci

#1373 Add invariant checking for scalars
  src/modules/schnorrsig/tests_exhaustive_impl.h
  src/scalar.h
  src/scalar_4x64_impl.h
  src/scalar_8x32_impl.h
  src/scalar_impl.h
  src/scalar_low_impl.h
  src/tests.c
Labels: assurance

#1403 ci, gha: Ensure only a single workflow processes `github.ref` at a time
  .github/workflows/ci.yml
Labels: ci

#1398 ci, gha: Add Windows jobs based on Linux image
  .cirrus.yml
  .github/actions/run-in-docker-action/action.yml
  .github/workflows/ci.yml
  ci/ci.sh
Labels: ci

#1405 ci: Drop no longer needed workaround
  .cirrus.yml
Labels: ci

#1396 ci, gha: Add "x86_64: Linux (Debian stable)" GitHub Actions job
  .cirrus.yml
  .github/actions/run-in-docker-action/action.yml
  .github/workflows/ci.yml
  ci/linux-debian.Dockerfile
Labels: ci

#1406 ci, gha: Move more non-x86_64 tasks from Cirrus CI to GitHub Actions
  .cirrus.yml
  .github/workflows/ci.yml
Labels: ci

#1409 ci: Move remained task from Cirrus to GitHub Actions
  .cirrus.yml
  .github/workflows/ci.yml
Labels: ci

#1411 ci: Make repetitive command the default one
  .github/actions/run-in-docker-action/action.yml
  .github/workflows/ci.yml
Labels: ci

#1412 ci: Switch macOS from Ventura to Monterey and add Valgrind
  .github/actions/install-homebrew-valgrind/action.yml
  .github/workflows/ci.yml
Labels: assurance, ci
