Repository bitcoin-core/secp256k1, pull requests merged in 2023-09, with the labels that each got.

#1414 ci/gha: Add ARM64 QEMU jobs for clang and clang-snapshot
  .github/workflows/ci.yml
  ci/linux-debian.Dockerfile
Labels: assurance, ci

#1413 ci: Add `release` job
  .github/workflows/ci.yml
Labels: assurance, ci, build

#1390 tests: Replace counting_illegal_callbacks with CHECK_ILLEGAL_VOID
  src/modules/ecdh/tests_impl.h
  src/modules/extrakeys/tests_impl.h
  src/modules/recovery/tests_impl.h
  src/modules/schnorrsig/tests_impl.h
  src/tests.c
Labels: assurance, refactor/smell

#1416 doc: Align documented scripts with CI ones
  doc/release-process.md
Labels: development, release

#1422 cmake: Install `libsecp256k1.pc` file
  .github/workflows/ci.yml
  cmake/GeneratePkgConfigFile.cmake
  src/CMakeLists.txt
Labels: build, needs-changelog

#1424 ci: Bump major versions for docker actions
  .github/actions/run-in-docker-action/action.yml
  .github/workflows/ci.yml
Labels: ci

#1395 tests: simplify `random_fe_non_zero` (remove loop limit and unneeded normalize)
  Makefile.am
  src/tests.c
  src/tests_exhaustive.c
  src/testutil.h
Labels: refactor/smell

#1426 ci/cirrus: Add native ARM64 jobs
  .cirrus.yml
  ci/linux-debian.Dockerfile
Labels: assurance, ci
