Repository bitcoin-core/secp256k1, pull requests merged in 2023-12, with the labels that each got.

#1393 Implement new policy for VERIFY_CHECK and #ifdef VERIFY (issue #1381)
  src/ecmult_const_impl.h
  src/field.h
  src/field_10x26_impl.h
  src/field_5x52_int128_impl.h
  src/field_impl.h
  src/group.h
  src/group_impl.h
  src/modinv32_impl.h
  src/modinv64_impl.h
  src/modules/ellswift/main_impl.h
  src/modules/ellswift/tests_impl.h
  src/scalar.h
  src/scalar_4x64_impl.h
  src/scalar_8x32_impl.h
  src/scalar_impl.h
  src/scalar_low_impl.h
  src/util.h
Labels: refactor/smell

#1446 field: Remove x86_64 asm
  CMakeLists.txt
  Makefile.am
  README.md
  configure.ac
  src/field_5x52_asm_impl.h
  src/field_5x52_impl.h
Labels: performance, needs-changelog

#1450 Add group.h ge/gej equality functions
  src/group.h
  src/group_impl.h
  src/modules/ellswift/tests_exhaustive_impl.h
  src/modules/ellswift/tests_impl.h
  src/tests.c
  src/tests_exhaustive.c
  src/testutil.h
Labels: refactor/smell

#1455 doc: improve secp256k1_fe_set_b32_mod doc
  src/field.h
Labels: refactor/smell

#1380 Add ABI checking tool for release process
  doc/release-process.md
  tools/check-abi.sh
Labels: assurance, release
