Repository bitcoin-core/secp256k1, pull requests merged in 2023-06, with the labels that each got.

#1341 docs: correct `pubkey` param descriptions for `secp256k1_keypair_{xonly_,}pub`
  include/secp256k1_extrakeys.h
Labels: documentation

#1339 scalar: refactor: use `secp256k1_{read,write}_be32` helpers
  src/scalar_4x64_impl.h
  src/scalar_8x32_impl.h
Labels: refactor

#1349 Normalize ge produced from secp256k1_pubkey_load
  src/secp256k1.c
Labels: bug

#1338 Drop no longer needed `#include "../include/secp256k1.h"`
  src/precompute_ecmult.c
  src/precompute_ecmult_gen.c
  src/precomputed_ecmult.c
  src/precomputed_ecmult.h
  src/precomputed_ecmult_gen.c
Labels: build

#1129 ElligatorSwift + integrated x-only DH
  .cirrus.yml
  CMakeLists.txt
  Makefile.am
  ci/cirrus.sh
  configure.ac
  doc/ellswift.md
  include/secp256k1_ellswift.h
  src/CMakeLists.txt
  src/bench.c
  src/ctime_tests.c
  src/group.h
  src/group_impl.h
  src/modules/ellswift/Makefile.am.include
  src/modules/ellswift/bench_impl.h
  src/modules/ellswift/main_impl.h
  src/modules/ellswift/tests_impl.h
  src/modules/schnorrsig/tests_impl.h
  src/secp256k1.c
  src/tests.c
Labels: feature

#1347 field: Document return value of fe_sqrt()
  src/field.h
Labels: documentation

#1336 Use `__shiftright128` intrinsic in `secp256k1_u128_rshift` on MSVC
  src/int128_struct_impl.h
Labels: performance

#1354 Add ellswift to CHANGELOG
  CHANGELOG.md
  include/secp256k1_ellswift.h
Labels: documentation

#1356 ci: Adjust Docker image to Debian 12 "bookworm"
  ci/cirrus.sh
  ci/linux-debian.Dockerfile
  src/ecmult_gen_compute_table_impl.h
Labels: ci

#1357 tests: refactor: take use of `secp256k1_ge_x_on_curve_var`
  src/tests.c
Labels: refactor
