Repository bitcoin-core/secp256k1, pull requests merged in 2023-07, with the labels that each got.

#1364 Avoid `-Wmaybe-uninitialized` when compiling with `gcc -O1`
  .cirrus.yml
  src/ecmult_impl.h
Labels: assurance, ci

#1370 Corrected some typos
  examples/examples_util.h
  include/secp256k1_ellswift.h
  sage/group_prover.sage
  src/ecmult.h
  src/ecmult_const_impl.h
  src/field.h
Labels: documentation

#1367 build: Improvements to symbol visibility logic on Windows (attempt 3)
  .cirrus.yml
  CHANGELOG.md
  Makefile.am
  configure.ac
  examples/CMakeLists.txt
  include/secp256k1.h
  include/secp256k1_ecdh.h
  include/secp256k1_ellswift.h
  include/secp256k1_schnorrsig.h
  src/CMakeLists.txt
Labels: documentation, build

#1344 group: save normalize_weak calls in `secp256k1_ge_is_valid_var`/`secp256k1_gej_eq_x_var`
  src/group.h
  src/group_impl.h
Labels: performance

#1371 Add exhaustive tests for ellswift (with create+decode roundtrip)
  src/modules/ellswift/Makefile.am.include
  src/modules/ellswift/tests_exhaustive_impl.h
  src/tests_exhaustive.c
Labels: assurance

#1340 clean up in-comment Sage code (refer to secp256k1_params.sage, update to Python3)
  src/ecdsa_impl.h
  src/tests.c
Labels: documentation

#1366 field: Use `restrict` consistently in fe_sqrt
  src/field_impl.h
Labels: refactor/smell

#1313 ci: Test on development snapshots of GCC and Clang
  .cirrus.yml
  ci/linux-debian.Dockerfile
Labels: assurance, ci, side-channel

#1298 Remove randomness tests
  src/testrand_impl.h
  src/tests.c
Labels: assurance

#1382 refactor: Drop unused cast
  src/hash_impl.h
Labels: refactor/smell
