Repository bitcoin-core/secp256k1, pull requests merged in 2024-05, with the labels that each got.

#1522 release: prepare for 0.5.0
  CHANGELOG.md
  CMakeLists.txt
  configure.ac
Labels: release

#1523 release cleanup: bump version after 0.5.0
  CHANGELOG.md
  CMakeLists.txt
  configure.ac
Labels: release

#1525 changelog: Correct 0.5.0 release date
  CHANGELOG.md
Labels: release

#1524 check-abi: explicitly provide public headers
  tools/check-abi.sh
Labels: assurance, release

#1526 cmake: Fix `check_arm32_assembly` when using as subproject
  cmake/CheckArm32Assembly.cmake
Labels: bug, build

#1528 tests: call `secp256k1_ecmult_multi_var` with a non-`NULL` error callback
  src/tests.c
Labels: bug, assurance

#1517 autotools: Disable eager MSan in ctime_tests
  .github/workflows/ci.yml
  build-aux/m4/bitcoin_secp.m4
  configure.ac
Labels: assurance, build, side-channel
