Repository bitcoin-core/secp256k1, pull requests merged in 2024-10, with the labels that each got.

#1479 Add module "musig" that implements MuSig2 multi-signatures (BIP 327)
  .cirrus.yml
  .github/workflows/ci.yml
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  Makefile.am
  README.md
  ci/ci.sh
  configure.ac
  doc/musig.md
  examples/CMakeLists.txt
  examples/musig.c
  include/secp256k1_musig.h
  src/CMakeLists.txt
  src/ctime_tests.c
  src/group.h
  src/group_impl.h
  src/modules/musig/Makefile.am.include
  src/modules/musig/keyagg.h
  src/modules/musig/keyagg_impl.h
  src/modules/musig/main_impl.h
  src/modules/musig/session.h
  src/modules/musig/session_impl.h
  src/modules/musig/tests_impl.h
  src/modules/musig/vectors.h
  src/secp256k1.c
  src/tests.c
  src/util.h
  tools/test_vectors_musig2_generate.py
Labels: feature

#1603 f can never equal -m
  src/modinv32_impl.h
  src/modinv64_impl.h
Labels: assurance, refactor/smell

#1599 #1570 improve examples: remove key generation loop
  examples/ecdh.c
  examples/ecdsa.c
  examples/ellswift.c
  examples/schnorr.c
  include/secp256k1.h
Labels: user-documentation, refactor/smell

#1553 cmake: Set top-level target output locations
  .github/workflows/ci.yml
  CMakeLists.txt
  examples/CMakeLists.txt
Labels: build

#1620 Remove unused scratch space from API
  CHANGELOG.md
  include/secp256k1.h
  src/scratch.h
  src/secp256k1.c
Labels: refactor/smell

#1595 build: 45839th attempt to fix symbol visibility on Windows
  include/secp256k1.h
Labels: build

#1619 musig: ctimetests: fix _declassify range for generated nonce points
  src/modules/musig/session_impl.h
Labels: bug, assurance

#1624 ci: Update macOS image
  .github/workflows/ci.yml
Labels: ci

#1625 util: Remove unused (u)int64_t formatting macros
  src/util.h
Labels: refactor/smell

#1582 cmake, test: Add `secp256k1_` prefix to test names
  examples/CMakeLists.txt
  src/CMakeLists.txt
Labels: build, refactor/smell
