Repository bitcoin-core/secp256k1, pull requests merged in 2024-04, with the labels that each got.

#1512 msan: notate more variable assignments from assembly code
  src/scalar_4x64_impl.h
Labels: assurance, refactor/smell

#1515 ci: Note affected clangs in comment on ASLR quirk
  .github/actions/run-in-docker-action/action.yml
Labels: assurance, ci, meta/development

#1058 Signed-digit multi-comb ecmult_gen algorithm
  .cirrus.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  CMakeLists.txt
  ci/ci.sh
  configure.ac
  src/ecmult_const_impl.h
  src/ecmult_gen.h
  src/ecmult_gen_compute_table.h
  src/ecmult_gen_compute_table_impl.h
  src/ecmult_gen_impl.h
  src/ecmult_impl.h
  src/precompute_ecmult_gen.c
  src/precomputed_ecmult_gen.c
  src/precomputed_ecmult_gen.h
  src/scalar.h
  src/scalar_4x64_impl.h
  src/scalar_8x32_impl.h
  src/scalar_low_impl.h
  src/tests.c
  src/tests_exhaustive.c
  src/util.h
Labels: performance
