Repository bitcoin-core/secp256k1, pull requests merged in 2024-11, with the labels that each got.

#1581 test, ci: Lower default iteration count to 16
  .cirrus.yml
  .github/workflows/ci.yml
  src/tests.c
Labels: assurance

#1628 Name public API structs
  include/secp256k1.h
  include/secp256k1_extrakeys.h
  include/secp256k1_musig.h
  include/secp256k1_recovery.h
  include/secp256k1_schnorrsig.h
Labels: feature, refactor/smell

#1579 Clear sensitive memory without getting optimized out (revival of #636)
  src/bench_ecmult.c
  src/ecmult_gen_impl.h
  src/ecmult_impl.h
  src/field.h
  src/field_10x26_impl.h
  src/field_5x52_impl.h
  src/field_impl.h
  src/group_impl.h
  src/hash.h
  src/hash_impl.h
  src/modules/ecdh/main_impl.h
  src/modules/ellswift/main_impl.h
  src/modules/musig/session_impl.h
  src/modules/schnorrsig/main_impl.h
  src/scalar_4x64_impl.h
  src/scalar_8x32_impl.h
  src/scalar_impl.h
  src/scalar_low_impl.h
  src/secp256k1.c
  src/tests.c
  src/testutil.h
  src/util.h
Labels: side-channel, needs-changelog

#1631 release: prepare for 0.6.0
  CHANGELOG.md
  CMakeLists.txt
  Makefile.am
  configure.ac
  src/modules/musig/session_impl.h
  tools/check-abi.sh
Labels: release
