Repository bitcoin-core/secp256k1, pull requests merged in 2024-01, with the labels that each got.

#1473 Fix typos
  CONTRIBUTING.md
  src/scalar_impl.h
Labels: refactor/smell, meta/development

#1474 tests: restore scalar_mul test
  src/tests.c
Labels: assurance, refactor/smell

#1476 include: make docs more consistent
  contrib/lax_der_parsing.h
  include/secp256k1.h
  include/secp256k1_ecdh.h
  include/secp256k1_ellswift.h
  include/secp256k1_extrakeys.h
  include/secp256k1_preallocated.h
  include/secp256k1_recovery.h
  include/secp256k1_schnorrsig.h
Labels: user-documentation, refactor/smell

#1480 Get rid of untested sizeof(secp256k1_ge_storage) == 64 code path
  src/assumptions.h
  src/secp256k1.c
  src/util.h
Labels: assurance

#1468 v0.4.1 release aftermath
  doc/release-process.md
  tools/check-abi.sh
Labels: meta/development, release

#1482 build: Clean up handling of module dependencies
  CMakeLists.txt
  configure.ac
Labels: build, refactor/smell

#1484 tests: Drop redundant _scalar_check_overflow calls
  src/tests.c
Labels: assurance, refactor/smell

#1483 cmake: Recommend native CMake commands in README
  README.md
Labels: user-documentation, build

#1486 ci: Update cache action
  .github/actions/install-homebrew-valgrind/action.yml
Labels: ci
