Repository bitcoin-core/secp256k1, pull requests merged in 2024-07, with the labels that each got.

#1565 cmake: Bump CMake minimum required version up to 3.16
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  doc/release-process.md
Labels: build

#1564 build, ci: Adjust the default size of the precomputed table for signing
  .github/workflows/ci.yml
  CMakeLists.txt
  configure.ac
Labels: ci, build, performance, needs-changelog

#1563 doc: Add convention for defaults
  CONTRIBUTING.md
Labels: assurance, meta/development

#1574 Fix compilation when extrakeys module isn't enabled
  .cirrus.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  ci/ci.sh
  src/tests.c
  src/testutil.h
Labels: bug, ci, build
