Repository bitcoin-core/secp256k1, pull requests merged in 2024-06, with the labels that each got.

#1532 cmake: Disable eager MSan in ctime_tests
  CMakeLists.txt
  build-aux/m4/bitcoin_secp.m4
  cmake/CheckMemorySanitizer.cmake
  configure.ac
Labels: assurance, build, side-channel

#1488 ci: Add native macOS arm64 job
  .github/workflows/ci.yml
Labels: assurance, ci

#1533 tests: refactor: tidy up util functions (#1491)
  src/modules/ecdh/tests_impl.h
  src/modules/ellswift/tests_impl.h
  src/modules/extrakeys/tests_impl.h
  src/modules/recovery/tests_impl.h
  src/modules/schnorrsig/tests_exhaustive_impl.h
  src/modules/schnorrsig/tests_impl.h
  src/testrand.h
  src/testrand_impl.h
  src/tests.c
  src/tests_exhaustive.c
  src/testutil.h
Labels: assurance, refactor/smell

#1529 cmake: Fix cache issue when integrating by downstream project
  CMakeLists.txt
Labels: build, refactor/smell

#1548 README: mention ellswift module
  README.md
Labels: user-documentation

#1545 cmake: Do not set `CTEST_TEST_TARGET_ALIAS`
  CMakeLists.txt
Labels: build

#1550 fix: typos in secp256k1.c
  src/secp256k1.c
Labels: refactor/smell

#1546 cmake: Rename `SECP256K1_LATE_CFLAGS` and switch to Bitcoin Core's approach
  CMakeLists.txt
  cmake/AllTargetsCompileOptions.cmake
Labels: build

#1543 cmake: Do not modify build types when integrating by downstream project
  CMakeLists.txt
Labels: bug, build

#1535 build: Replace hardcoded "auto" value with default one
  .cirrus.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  configure.ac
Labels: build

#1555 Fixed O3 replacement
  CMakeLists.txt
Labels: build
