Repository bitcoin-core/secp256k1, pull requests merged in 2025-03, with the labels that each got.

#1614 Add _ge_set_all_gej and use it in musig for own public nonces
  src/group.h
  src/group_impl.h
  src/modules/musig/session_impl.h
  src/tests.c
Labels: performance

#1656 musig: Fix clearing of pubnonces
  src/modules/musig/session_impl.h
Labels: bug

#1647 cmake: Adjust diagnostic flags for `clang-cl`
  .github/workflows/ci.yml
  CMakeLists.txt
Labels: ci, feature, build

#1655 gha: Print all *.log files, in a separate action
  .github/actions/print-logs/action.yml
  .github/workflows/ci.yml
Labels: assurance, ci

#1359 Fix symbol visibility issues, add test for it
  .cirrus.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  Makefile.am
  ci/ci.sh
  ci/linux-debian.Dockerfile
  configure.ac
  src/precomputed_ecmult.h
  src/precomputed_ecmult_gen.h
  src/util_local_visibility.h
  tools/symbol-check.py
Labels: assurance, build

#1657 tests: remove unused uncounting_illegal_callback_fn
  src/tests.c
Labels: assurance, refactor/smell
